version: '3'
services:
  python:
    image: python-flask
    container_name: python-flask
    hostname: python-flask
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-python
    ports:
    - "10000:5000"
    volumes:
    - ./python-flask:/workspace
    tty: true
#    networks:
#      - app-network

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-mysql
    restart: on-failure
    env_file:
      - .env
    environment:
#      MYSQL_USER: sample_user #新たにユーザーを作成する
#      MYSQL_DATABASE: sample_db #新たにDBを作成する
      TZ: "Asia/Tokyo"
      BIND-ADDRESS: 0.0.0.0
    ports:
      - "3306:3306"
    # データを永続化させる場合
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir(ホスト側は空のディレクトリをマウントしないと初期データは登録されない！)
      - ./mysql/db:/var/lib/mysql
    command:
      --secure-file-priv="/docker-entrypoint-initdb.d"
    tty: true
#    networks:
#      - app-network

#networks:
#    app-network:

