FROM python:3.9
WORKDIR /workspace

# 本番環境ではマウントせずにコピーする
COPY python-flask/ /workspace/

RUN apt-get update &&\
 pip install --upgrade pip &&\
 pip install pipenv &&\
 pipenv install &&\
 pipenv install --system

CMD python app.py