FROM python:3.9
WORKDIR /workspace

COPY ./python-flask/Pipfile ./

RUN apt-get update &&\
 pip install --upgrade pip &&\
 pip install pipenv &&\
 pipenv install &&\
 pipenv install --system

CMD python app.py