name: Deploy docker-compose to GCE

on:
  push:
    branches: [ production ]

jobs:
  build-deploy:
    name: Build Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: execute via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            touch ~/a.txt
            # source ~/deploy.sh
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER_NAME }}
          key: ${{ secrets.ID_RSA_GCE}}
