name: Deploy docker-compose to GCE

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    name: Build Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.ID_RSA_GCE }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
    - name: Deploy
      run: |
        ssh seal-git@${SERVER_HOST} 'bash -s ~/deploy.sh'
      env:
        SERVER_HOST: 34.146.166.191 # 接続先のGCEの外部IP
