name: Deploy docker-compose to GCE

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    name: Build Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup SSH
        run: |
          # 初期状態では.sshがなかったので作成
          mkdir ~/.ssh
          # SSH鍵を環境変数からデコード
          echo ${SSH_KEY} > ~/.ssh/my-ssh-key
          echo ${SSH_KEY_PUB} > ~/.ssh/my-ssh-key.pub
          chmod 600 ~/.ssh/my-ssh-key
          echo ~/.ssh/my-ssh-key.pub
        env:
          SERVER_HOST: 34.146.166.191 # 接続先のGCEの外部IP
          SSH_KEY: ${{ secrets.ID_RSA_GCE }}
          SSH_KEY_PUB: ${{ secrets.ID_RSA_GCE_PUB }}
      - name: Deploy
        run: |
          ssh yuki@${SERVER_HOST} -i ~/.ssh/my-ssh-key 'bash -s ~/deploy.sh'
        env:
          SERVER_HOST: 34.146.166.191 # 接続先のGCEの外部IP
